### PR TITLE
fix(py38): restore Python 3.8 import compatibility for v1.6.0 wheel

### PR DESCRIPTION
**Pull request by zengguizhang**
## Summary

The cp38 wheel of `wujihandpy` 1.6.0 (currently on PyPI) crashes on
`import wujihandpy` with `ImportError: cannot import name 'Annotated'
from 'typing'`, leaving every downstream API (Hand / Finger / Joint /
filter / tactile / ...) unreachable on Python 3.8. `pyproject.toml`
still declares `requires-python = ">=3.8"` and cibuildwheel still
builds and publishes a cp38 wheel, so pip happily installs the broken
artifact for 3.8 users.

Root cause was introduced by PR #72 (commit bfc08cc, feat(upgrade-check):
show firmware upgrade banner on Hand() construct), which added two
typing constructs that postdate 3.8 to the new `Hand` Python wrapper:

- top-level `from typing import Annotated` — `Annotated` only landed in
  stdlib `typing` in 3.9, so module import explodes at parse time on 3.8.
- `serial_number: str | None` and `mask: Annotated[...] | None` — PEP 604
  unions only landed in 3.10, so `typing.get_type_hints(Hand.__init__)`
  (Sphinx autodoc with typehints, FastAPI/Pydantic schema generation,
  etc.) still raises on 3.8/3.9 even after the import is fixed.

`from __future__ import annotations` was already enabled, but it only
defers evaluation — it doesn't paper over a missing top-level symbol.

## What this PR changes

Scoped to `src/wujihandpy/__init__.py` (code) + `pyproject.toml`
(metadata) + `CHANGELOG.md`:

1. **`Annotated` import deferred to the `TYPE_CHECKING` block** — fixes
   the actual `ImportError` on 3.8. Static type checkers (mypy / pyright)
   still resolve the symbol the same way; the runtime never references
   it because `from __future__ import annotations` keeps the `mask`
   annotation a string.
2. **`X | None` → `Optional[X]`** for both `serial_number` and `mask`,
   so the annotation strings are eval-safe on every supported interpreter
   if/when something does call `typing.get_type_hints` on this method.
3. **Metadata cleanup**: `authors` / `maintainers` unified to the
   `Wuji Technology / support@wuji.tech` identity (a personal Gmail had
   been left in `authors` since the original packaging).
4. **CHANGELOG**: one-line `Fixed` entry under `[Unreleased]` describing
   the 3.8 import regression.

### What this PR explicitly does NOT do

An intermediate revision of this branch routed `Annotated` through a
runtime `sys.version_info` gate plus `typing_extensions; python_version
< '3.9'` as a conditional dependency. That was reverted (commit
73a9acb) once it became clear the backport provided **zero
user-observable behavior**: with `from __future__ import annotations`
the `Annotated` name is never evaluated at runtime, and the only path
that would force evaluation — `typing.get_type_hints(Hand.__init__)` —
still fails downstream on the unresolved `numpy` regardless of whether
`Annotated` is importable. Net result on 3.8: zero new runtime deps,
identical user-facing behavior.

## Known remaining gap (out of scope)

`numpy` / `numpy.typing` and `Annotated` are all under `TYPE_CHECKING`.
So `typing.get_type_hints(wujihandpy.Hand.__init__)` continues to raise
a `NameError` on every Python version — this is a pre-existing issue
unrelated to 3.8 compatibility, and it only manifests for callers that
explicitly invoke `get_type_hints` (Sphinx autodoc with
`autodoc_typehints` enabled, FastAPI/Pydantic schema generation).
Regular SDK usage — `import wujihandpy`, `Hand()` construction,
read/write methods, `inspect.signature(...)`, `help(...)` — is fully
unaffected. Resolving this would require promoting `numpy` and
`Annotated` to runtime imports, costing ~50 ms of startup time for a
feature no one currently consumes, so it is deliberately left out and
can be addressed in a follow-up if/when a real consumer surfaces.

## Test plan

Verified end-to-end in throwaway Docker containers (`--rm`, images
removed after each run) against the **final** state of this branch
(commit 73a9acb onward — no `typing_extensions` involved):

### Python 3.8.20 (the broken target)

`typing_extensions` deliberately NOT installed in the container.

| Check | Before fix (stock v1.6.0) | After fix overlay |
|---|---|---|
| `import wujihandpy` | `ImportError: cannot import name 'Annotated' from 'typing'` | OK, version reports 1.6.0 |
| `wujihandpy.Hand` class | unreachable | `<class 'wujihandpy.Hand'>` |
| C++ `_core` init | unreachable | OK (`SDK v1.6.0 initialized` log printed) |
| `inspect.signature(Hand.__init__)` | unreachable | OK, 5 params, mask annotation = `'Optional[Annotated[numpy.typing.ArrayLike, numpy.bool_]]'` |
| `typing.get_type_hints(Hand.__init__)` | unreachable | `NameError` (pre-existing, documented above) |

### Python 3.12.13 (regression check — interpreter not affected by the original bug)

| Check | Stock v1.6.0 | After fix overlay |
|---|---|---|
| `import wujihandpy` | OK | OK |
| `wujihandpy.Hand` class | OK | OK |
| C++ `_core` init | OK (`SDK v1.6.0 initialized`) | OK (`SDK v1.6.0 initialized`) |
| `inspect.signature(Hand.__init__)` | OK | OK, 5 params, mask annotation as expected string |
| `typing.get_type_hints(Hand.__init__)` | `NameError: name 'numpy' is not defined` | `NameError: name 'Annotated' is not defined` (same kind of pre-existing unreachable-name issue, now on `Annotated` since the import sits under `TYPE_CHECKING`) |

Verification protocol per container:
1. `pip install wujihandpy==1.6.0` from PyPI (the broken artifact).
2. Run `python -c "import wujihandpy"` to observe stock behavior.
3. Overlay this PR's `src/wujihandpy/__init__.py` onto the installed
   site-packages location, re-run `import wujihandpy` + the
   introspection probes above. **No `pip install typing_extensions`**.
4. `docker image rm` the python image after each run.

- [ ] CI green on all build matrix entries (manylinux cp38–cp3xx)
- [ ] After merge: cut a v1.6.1 patch release and yank v1.6.0 from
      PyPI so 3.8 users stop pulling the broken wheel

Resolve swd-1210

## 发行说明

* **Bug Fixes**
  * 修复了在 Python 3.8 环境下导入时触发的 ImportError，恢复兼容性。

* **Refactor**
  * 调整了类型注解和运行时依赖处理，减少对运行时类型符号的依赖并改善静态检查兼容性。

* **Chores**
  * 更新了项目元数据信息（作者/维护联系信息）。

[Review Change Stack](https://app.coderabbit.ai/change-stack/wuji-technology/wujihandpy/pull/78?utm_source=github_walkthrough&utm_medium=github&utm_campaign=change_stack)

### CODE REVIEW

**Comment by zengguizhang** [comment]
@coderabbitai review

File: src/wujihandpy/__init__.py [hunk 1]
```diff
@@ -71,12 +78,12 @@ class Hand(_core.Hand):
...
         *,
-        side: str | None = None,
+        side: Optional[str] = None,
         usb_pid: SupportsIndex = 0x2000,
         usb_vid: SupportsIndex = 0x0483,
-        mask: Annotated[numpy.typing.ArrayLike, numpy.bool_] | None = None,
+        mask: Optional[Annotated[numpy.typing.ArrayLike, numpy.bool_]] = None,
     ) -> None:
         args, kwargs = _resolve_super_init_args(serial_number, side, usb_pid, usb_vid, mask)
         super().__init__(*args, **kwargs)
```
[the remark this answers is not in the document]
Comment (zengguizhang) [reply src/wujihandpy/__init__.py:89]: 库的 stub 约定就是：只为 pybind11 模块（_core/*.pyi）生成 stub，纯 Python 文件不写 .pyi。证据在 update_stubs.py:9——只跑 pybind11_stubgen.main(["wujihandpy._core", "-o", "src"])，专门服务于 C++ 绑定（没有 Python                                          
  源文件可读）。_upgrade_check.py、_version.py 同样没有 .pyi。

**Review by RigoLigoRLC — APPROVED** [review]
